param(
    [string]$VertSpv,
    [string]$FragSpv,
    [string]$OutputHeader
)
function Read-SpvWords([string]$Path) {
    $stream = [System.IO.File]::OpenRead($Path)
    $words = @()
    $buf = New-Object byte[] 4
    while ($stream.Read($buf, 0, 4) -eq 4) {
        $words += [System.BitConverter]::ToUInt32($buf, 0)
    }
    $stream.Close()
    return $words
}
$vertWords = Read-SpvWords $VertSpv
$fragWords = Read-SpvWords $FragSpv
$vertStr = ($vertWords | ForEach-Object { "0x{0:X8}," -f $_ }) -join " "
$fragStr = ($fragWords | ForEach-Object { "0x{0:X8}," -f $_ }) -join " "
$header = @"
// Auto-generated by CMake — do not edit
#pragma once
#include <cstdint>
#include <vector>
namespace kwik::shader {
    inline const std::vector<std::uint32_t> kRectVert = { $vertStr };
    inline const std::vector<std::uint32_t> kRectFrag = { $fragStr };
}
"@
[System.IO.File]::WriteAllText($OutputHeader, $header, [System.Text.UTF8Encoding]::new($false))