cmake_minimum_required(VERSION 3.21)
function(spv_to_bytes VAR FILE_PATH)
    file(READ "${FILE_PATH}" raw_hex HEX)
    string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1, " formatted "${raw_hex}")
    set("${VAR}" "${formatted}" PARENT_SCOPE)
endfunction()
if(NOT DEFINED NAME)
    set(NAME "kRect")
endif()
spv_to_bytes(VERT_BYTES "${VERT_SPV}")
spv_to_bytes(FRAG_BYTES "${FRAG_SPV}")
file(WRITE "${OUTPUT}"
    "// Auto-generated by CMake — do not edit\n"
    "#pragma once\n"
    "#include <cstdint>\n\n"
    "namespace kwik::shader {\n"
    "inline const std::uint8_t ${NAME}Vert[] = { ${VERT_BYTES} };\n"
    "inline const std::size_t ${NAME}VertSize = sizeof(${NAME}Vert);\n"
    "inline const std::uint8_t ${NAME}Frag[] = { ${FRAG_BYTES} };\n"
    "inline const std::size_t ${NAME}FragSize = sizeof(${NAME}Frag);\n"
    "}\n"
)

